%YAML 1.2
---

distribution_name: 'yiffOS'

internet_connection_required: yes

internet_checker_url: 'http://nmcheck.gnome.org/check_network_status.txt'

fixed_language: no

suggested_languages:
    - 'ar'
    - 'de'
    - 'en'
    - 'es'
    - 'fr'
    - 'ja'
    - 'nl'
    - 'ru'
    - 'zh'

welcome_page:
    logo    : '/etc/os-installer/bits/logo.png'
    text    : 'Welcome to the yiffOS installer! This is an early W.I.P preview of yiffOS 0.2.0, expect bugs and breakages.'
    usage   : yes

minimum_disk_size: 10

offer_disk_encryption: no

skip_user: no
skip_locale: no

browser_cmd: 'epiphany'
disks_cmd  : 'gnome-disks'
wifi_cmd   : 'gnome-control-center wifi'